baseurl = "https://www.karansampath.com"
copyright = "© Karan Sampath"
title = "Karan Sampath"
enablerobotstxt = true
theme="archie"
languagecode = "en-us"
timezone = "America/Los_Angeles"
titlecasestyle = "Go"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
favicon = "/images/gordian.webp"
mode="toggle" # color-mode → light,dark,toggle or auto
useCDN=true
subtitle = "Personal website"
description = "Personal website"
mathjax = false # enable MathJax support
katex = false # enable KaTeX support

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/karansampath"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/karan_sampath"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/karansampath/"

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:me@karansampath.com"

[[menu.main]]
name = "Home"
url = "/"
weight = 1


[[menu.main]]
name = "Blog"
url = "/blog"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 4

[[menu.main]]
name = "Interests"
url = "/interests"
weight = 5

