baseurl = "https://www.karansampath.com"
copyright = "Â© Karan Sampath"
enablerobotstxt = true
languagecode = "en-us"
paginate = 50
timezone = "America/New_York"
titlecasestyle = "Go"

[params.paige]
credit = '<a>Karan Sampath</a>'

[languages.en]
title = "Karan"
weight = 10

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[languages.en.menu.main]]
identifier = "About Me"
name = "About Me"
url = "/about/"
weight = 20

[[languages.en.menu.main]]
identifier = "favorites"
name = "Favorites"
url = "/favorites/"
weight = 30

[[languages.en.menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 40

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noclasses = false

[markup.tableofcontents]
endlevel = 6
ordered = true
startlevel = 2

[[module.imports]]
path = "github.com/willfaught/paige"

[outputs]
home = ["atom", "html", "json", "rss"]
section = ["atom", "html", "rss"]
taxonomy = ["atom", "html", "rss"]
term = ["atom", "html", "rss"]

[params.authors.karan-sampath]
default = true
email = "karan.sampath02@gmail.com"
name = "Karan Sampath"
url = "https://www.karansampath.com"

[params.paige.git]
commit_url = "https://github.com/karansampath/karansampath.github.io/commit/%s"

[params.paige.site]
disable_breadcrumbs = true
disable_credit = true

[params.paige.list_page]
disable_authors = true
disable_date = true
disable_keywords = true
disable_reading_time = true
disable_series = true
disable_summary = true

[params.paige.page]
disable_authors = true
disable_date = true
disable_keywords = true
disable_next = true
disable_prev = true
disable_reading_time = true
disable_series = true
disable_toc = true

[[params.paige.feed.atom.authors]]
email = "karan.sampath02@gmail.com"
name = "Karan Sampath"
url = "https://www.karansampath.com"

[params.paige.feed.rss]
managing_editor = "karan.sampath02@gmail.com (Karan Sampath)"
web_master = "karan.sampath02@gmail.com (Karan Sampath)"

[params.paige.file_link]
content = "Edit this page"
disable = true
url = "https://github.com/karansampath/karansampath.github.io/edit/master/content/%s"

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"
